// <auto-generated/>
// AUTO GENERATED. DO NOT EDIT.

public static class CombatGameplayTags
{
    public const GameplayTagDomain Domain = GameplayTagDomain.Combat;

    public static readonly GameplayTag Ability = new GameplayTag(Domain, 0x01000000u, 0xFF000000u); // @Tag:Ability
    public static readonly GameplayTag Ability_Attack = new GameplayTag(Domain, 0x01010000u, 0xFFFF0000u); // @Tag:Ability.Attack
    public static readonly GameplayTag Ability_Block = new GameplayTag(Domain, 0x01050000u, 0xFFFF0000u); // @Tag:Ability.Block
    public static readonly GameplayTag Ability_Born = new GameplayTag(Domain, 0x01020000u, 0xFFFF0000u); // @Tag:Ability.Born
    public static readonly GameplayTag Ability_Death = new GameplayTag(Domain, 0x01030000u, 0xFFFF0000u); // @Tag:Ability.Death
    public static readonly GameplayTag Ability_Skill = new GameplayTag(Domain, 0x01040000u, 0xFFFF0000u); // @Tag:Ability.Skill
    public static readonly GameplayTag Cue = new GameplayTag(Domain, 0x02000000u, 0xFF000000u); // @Tag:Cue
    public static readonly GameplayTag Cue_Hit = new GameplayTag(Domain, 0x02010000u, 0xFFFF0000u); // @Tag:Cue.Hit
    public static readonly GameplayTag Cue_Poison = new GameplayTag(Domain, 0x02020000u, 0xFFFF0000u); // @Tag:Cue.Poison
    public static readonly GameplayTag State = new GameplayTag(Domain, 0x03000000u, 0xFF000000u); // @Tag:State
    public static readonly GameplayTag State_Attacking = new GameplayTag(Domain, 0x03010000u, 0xFFFF0000u); // @Tag:State.Attacking
    public static readonly GameplayTag State_BlockCooldown = new GameplayTag(Domain, 0x03080000u, 0xFFFF0000u); // @Tag:State.BlockCooldown
    public static readonly GameplayTag State_BornInvincible = new GameplayTag(Domain, 0x03090000u, 0xFFFF0000u); // @Tag:State.BornInvincible
    public static readonly GameplayTag State_Casting = new GameplayTag(Domain, 0x03020000u, 0xFFFF0000u); // @Tag:State.Casting
    public static readonly GameplayTag State_Dead = new GameplayTag(Domain, 0x03030000u, 0xFFFF0000u); // @Tag:State.Dead
    public static readonly GameplayTag State_Hit = new GameplayTag(Domain, 0x03040000u, 0xFFFF0000u); // @Tag:State.Hit
    public static readonly GameplayTag State_Invincible = new GameplayTag(Domain, 0x03050000u, 0xFFFF0000u); // @Tag:State.Invincible
    public static readonly GameplayTag State_Moving = new GameplayTag(Domain, 0x03060000u, 0xFFFF0000u); // @Tag:State.Moving
    public static readonly GameplayTag State_Poisoned = new GameplayTag(Domain, 0x03070000u, 0xFFFF0000u); // @Tag:State.Poisoned
    public static readonly GameplayTag State_Rooted = new GameplayTag(Domain, 0x030B0000u, 0xFFFF0000u); // @Tag:State.Rooted
    public static readonly GameplayTag State_Silenced = new GameplayTag(Domain, 0x030C0000u, 0xFFFF0000u); // @Tag:State.Silenced
    public static readonly GameplayTag State_Stunned = new GameplayTag(Domain, 0x030A0000u, 0xFFFF0000u); // @Tag:State.Stunned
    public static readonly GameplayTag State_Untargetable = new GameplayTag(Domain, 0x030D0000u, 0xFFFF0000u); // @Tag:State.Untargetable
    public static readonly GameplayTag Trigger = new GameplayTag(Domain, 0x04000000u, 0xFF000000u); // @Tag:Trigger
    public static readonly GameplayTag Trigger_OnDamageTaken = new GameplayTag(Domain, 0x04010000u, 0xFFFF0000u); // @Tag:Trigger.OnDamageTaken
    public static readonly GameplayTag Trigger_OnKill = new GameplayTag(Domain, 0x04020000u, 0xFFFF0000u); // @Tag:Trigger.OnKill
}
