// <auto-generated>
// Generated UI binding code. Do not edit manually.
// </auto-generated>
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI.Generated
{
    public sealed class LoadingViewBinder : global::UIViewBinder
    {
        public LoadingViewBinder(global::CSharpUIBindBehaviour source) : base(source) { }

        public global::UIImageRef Image_Logo => Img("Image_Logo");
        public GameObject Image_LogoGameObject => Image_Logo.GameObject;
        public Image Image_LogoImage => Image_Logo.Get<Image>();

        public global::UIImageRef img_Fill => Img("img_Fill");
        public GameObject img_FillGameObject => img_Fill.GameObject;
        public Image img_FillImage => img_Fill.Get<Image>();

        public global::UITextRef txt_ProgressNum => Txt("txt_ProgressNum");
        public GameObject txt_ProgressNumGameObject => txt_ProgressNum.GameObject;
        public TextMeshProUGUI txt_ProgressNumText => txt_ProgressNum.Get<TextMeshProUGUI>();

        public global::UITextRef txt_Strategy => Txt("txt_Strategy");
        public GameObject txt_StrategyGameObject => txt_Strategy.GameObject;
        public TextMeshProUGUI txt_StrategyText => txt_Strategy.Get<TextMeshProUGUI>();
    }
}
