// <auto-generated>
// Generated by CSharpUIBindCodeGenerator. Do not edit manually.
// </auto-generated>
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Game.UI.Generated
{
    public sealed class LoginViewBinder : UIViewBinder
    {
        public LoginViewBinder(CSharpUIBindBehaviour source) : base(source) { }

    }
}
