#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public static class AIGeneratedUIViewCodeGenerator
{
    public static void GenerateRecursive(CSharpUIBindBehaviour root)
    {
        if (root == null)
            return;

        var binders = root.GetComponentsInChildren<CSharpUIBindBehaviour>(true);
        foreach (var binder in binders)
        {
            if (binder.AutoGenerateViewBindingsOnPrefabSave)
                Generate(binder);
        }
    }

    public static void Generate(CSharpUIBindBehaviour bind)
    {
        if (bind == null)
            return;

        bind.RefreshBindingsInEditor(false);

        var folder = bind.GetGeneratedCodeFolderInEditor();
        if (!Directory.Exists(folder))
            Directory.CreateDirectory(folder);

        var className = GetViewClassName(bind);
        var code = BuildViewCode(bind, bind.GeneratedViewNamespace, className);
        var path = Path.Combine(folder, className + ".g.cs");

        File.WriteAllText(path, code, Encoding.UTF8);
        AssetDatabase.Refresh();
        Debug.Log($"[AIGeneratedUIViewCodeGenerator] Generated: {path}", bind);
    }

    private static string BuildViewCode(CSharpUIBindBehaviour bind, string ns, string className)
    {
        var sb = new StringBuilder();
        var indent = string.IsNullOrWhiteSpace(ns) ? string.Empty : "    ";
        var usedMembers = new HashSet<string>();
        var assignments = new List<string>();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by AIGeneratedUIViewCodeGenerator. Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns.Trim()}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}public partial class {className} : IUIViewGeneratedBinding");
        sb.AppendLine($"{indent}{{");

        foreach (var item in bind.Items)
            AppendMembers(sb, assignments, usedMembers, indent + "    ", item);

        sb.AppendLine($"{indent}    void IUIViewGeneratedBinding.BindGeneratedUI(UIViewBinder binder)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (binder == null)");
        sb.AppendLine($"{indent}            throw new global::System.ArgumentNullException(nameof(binder));");
        sb.AppendLine();

        foreach (var assignment in assignments)
            sb.AppendLine($"{indent}        {assignment}");

        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrWhiteSpace(ns))
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendMembers(
        StringBuilder sb,
        List<string> assignments,
        HashSet<string> usedMembers,
        string indent,
        UIBindItem item)
    {
        if (item == null || string.IsNullOrWhiteSpace(item.Key))
            return;

        var key = item.Key;
        var baseName = UIBindNameUtility.ToSafeIdentifier(key);
        var escapedKey = EscapeStringLiteral(key);

        if (item.IsSubBinder)
        {
            var refName = ReserveMemberName(usedMembers, baseName);
            sb.AppendLine($"{indent}protected UIObjectRef {refName} {{ get; private set; }}");
            assignments.Add($"{refName} = binder.Get(\"{escapedKey}\");");

            if (!string.IsNullOrWhiteSpace(item.NestedBinderTypeName))
            {
                var binderName = ReserveMemberName(usedMembers, baseName + "Binder");
                var nestedTypeName = ToGlobalTypeName(item.NestedBinderTypeName.Trim());
                sb.AppendLine($"{indent}protected {nestedTypeName} {binderName} {{ get; private set; }}");
                assignments.Add($"{binderName} = binder.GetBinder<{nestedTypeName}>(\"{escapedKey}\");");
            }
            else
            {
                var binderName = ReserveMemberName(usedMembers, baseName + "Binder");
                sb.AppendLine($"{indent}protected UIViewBinder {binderName} {{ get; private set; }}");
                assignments.Add($"{binderName} = binder.GetBinder(\"{escapedKey}\");");
            }

            sb.AppendLine();
            return;
        }

        var refType = GetRefType(item);
        var getter = GetGetterMethod(item);
        var memberName = ReserveMemberName(usedMembers, baseName);

        sb.AppendLine($"{indent}protected {refType} {memberName} {{ get; private set; }}");
        assignments.Add($"{memberName} = binder.{getter}(\"{escapedKey}\");");

        if (item.GameObject != null)
        {
            var goName = ReserveMemberName(usedMembers, baseName + "GameObject");
            sb.AppendLine($"{indent}protected GameObject {goName} {{ get; private set; }}");
            assignments.Add($"{goName} = {memberName}.GameObject;");
        }

        AppendComponentMembers(sb, assignments, usedMembers, indent, item, baseName, escapedKey);
        sb.AppendLine();
    }

    private static void AppendComponentMembers(
        StringBuilder sb,
        List<string> assignments,
        HashSet<string> usedMembers,
        string indent,
        UIBindItem item,
        string baseName,
        string escapedKey)
    {
        if (item.Components == null)
            return;

        foreach (var componentRef in item.Components)
        {
            if (componentRef == null || componentRef.Component == null)
                continue;

            var typeName = GetComponentTypeName(componentRef.Component.GetType());
            var suffix = GetComponentSuffix(componentRef);
            var memberName = ReserveMemberName(usedMembers, baseName + suffix);

            sb.AppendLine($"{indent}protected {typeName} {memberName} {{ get; private set; }}");
            assignments.Add($"{memberName} = binder.Get<{typeName}>(\"{escapedKey}\");");
        }
    }

    private static string GetViewClassName(CSharpUIBindBehaviour bind)
    {
        var raw = bind.GeneratedViewClassName;

        if (string.IsNullOrWhiteSpace(raw))
            raw = bind.GeneratedClassName;

        if (string.IsNullOrWhiteSpace(raw))
            raw = UIBindNameUtility.CleanGameObjectName(bind.gameObject.name);

        raw = raw.Trim();
        if (raw.EndsWith("Binder", StringComparison.Ordinal) && raw.Length > "Binder".Length)
            raw = raw.Substring(0, raw.Length - "Binder".Length);

        return UIBindNameUtility.ToSafeIdentifier(raw);
    }

    private static string GetRefType(UIBindItem item)
    {
        return item.MainAlias switch
        {
            "Button" => "UIButtonRef",
            "Text" => "UITextRef",
            "TMPText" => "UITextRef",
            "Image" => "UIImageRef",
            "ScrollRect" => "UIScrollRef",
            _ => "UIObjectRef"
        };
    }

    private static string GetGetterMethod(UIBindItem item)
    {
        return item.MainAlias switch
        {
            "Button" => "Btn",
            "Text" => "Txt",
            "TMPText" => "Txt",
            "Image" => "Img",
            "ScrollRect" => "Scroll",
            _ => "Get"
        };
    }

    private static string GetComponentTypeName(Type type)
    {
        if (type == typeof(RectTransform)) return "RectTransform";
        if (type == typeof(CanvasGroup)) return "CanvasGroup";
        if (type == typeof(Button)) return "Button";
        if (type == typeof(Image)) return "Image";
        if (type == typeof(RawImage)) return "RawImage";
        if (type == typeof(Text)) return "Text";
        if (type == typeof(TextMeshProUGUI)) return "TextMeshProUGUI";
        if (type == typeof(Toggle)) return "Toggle";
        if (type == typeof(ToggleGroup)) return "ToggleGroup";
        if (type == typeof(Slider)) return "Slider";
        if (type == typeof(Scrollbar)) return "Scrollbar";
        if (type == typeof(ScrollRect)) return "ScrollRect";
        if (type == typeof(Dropdown)) return "Dropdown";
        if (type == typeof(TMP_Dropdown)) return "TMP_Dropdown";
        if (type == typeof(InputField)) return "InputField";
        if (type == typeof(TMP_InputField)) return "TMP_InputField";
        if (type == typeof(Animator)) return "Animator";
        if (type == typeof(Animation)) return "Animation";

        return ToGlobalTypeName(type.FullName);
    }

    private static string GetComponentSuffix(UIBindComponentRef componentRef)
    {
        return componentRef.Alias switch
        {
            "RectTransform" => "Rect",
            "TMPText" => "Text",
            "TMPInputField" => "Input",
            "InputField" => "Input",
            "TMPDropdown" => "Dropdown",
            _ => UIBindNameUtility.ToSafeIdentifier(componentRef.Alias)
        };
    }

    private static string ReserveMemberName(HashSet<string> usedMembers, string preferredName)
    {
        var safeName = UIBindNameUtility.ToSafeIdentifier(preferredName);
        var candidate = safeName;
        var index = 2;

        while (!usedMembers.Add(candidate))
            candidate = safeName + index++;

        return candidate;
    }

    private static string ToGlobalTypeName(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return "global::System.Object";

        return typeName.StartsWith("global::", StringComparison.Ordinal)
            ? typeName
            : "global::" + typeName;
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}
#endif
