// <auto-generated/>
// AUTO GENERATED. DO NOT EDIT.

public static class CombatGameplayTags
{
    public static readonly GameplayTag Ability_Attack = new GameplayTag(0x01010000u, 0xFFFF0000u); // @Tag:Ability.Attack
    public static readonly GameplayTag Ability_Born = new GameplayTag(0x01020000u, 0xFFFF0000u); // @Tag:Ability.Born
    public static readonly GameplayTag Ability_Death = new GameplayTag(0x01030000u, 0xFFFF0000u); // @Tag:Ability.Death
    public static readonly GameplayTag Ability_Skill = new GameplayTag(0x01040000u, 0xFFFF0000u); // @Tag:Ability.Skill
    public static readonly GameplayTag Cue_Hit = new GameplayTag(0x02010000u, 0xFFFF0000u); // @Tag:Cue.Hit
    public static readonly GameplayTag Cue_Poison = new GameplayTag(0x02020000u, 0xFFFF0000u); // @Tag:Cue.Poison
    public static readonly GameplayTag State_Attacking = new GameplayTag(0x03010000u, 0xFFFF0000u); // @Tag:State.Attacking
    public static readonly GameplayTag State_Casting = new GameplayTag(0x03020000u, 0xFFFF0000u); // @Tag:State.Casting
    public static readonly GameplayTag State_Dead = new GameplayTag(0x03030000u, 0xFFFF0000u); // @Tag:State.Dead
    public static readonly GameplayTag State_Hit = new GameplayTag(0x03040000u, 0xFFFF0000u); // @Tag:State.Hit
    public static readonly GameplayTag State_Invincible = new GameplayTag(0x03050000u, 0xFFFF0000u); // @Tag:State.Invincible
    public static readonly GameplayTag State_Moving = new GameplayTag(0x03060000u, 0xFFFF0000u); // @Tag:State.Moving
    public static readonly GameplayTag State_Poisoned = new GameplayTag(0x03070000u, 0xFFFF0000u); // @Tag:State.Poisoned
    public static readonly GameplayTag Trigger_OnDamageTaken = new GameplayTag(0x04010000u, 0xFFFF0000u); // @Tag:Trigger.OnDamageTaken
    public static readonly GameplayTag Trigger_OnKill = new GameplayTag(0x04020000u, 0xFFFF0000u); // @Tag:Trigger.OnKill
}