// <auto-generated/>
// AUTO GENERATED from GameplayTagDatabase PVEGameTags
public static class PVEGameTags
{
    public static readonly GameplayTag State = new GameplayTag(0x01000000u, 0xFF000000u); // @Tag:State
}
