#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class GameplayTagCodeGenerator
{
    private sealed class TagNode
    {
        public string Name;
        public string FullPath;
        public int Id;
        public TagNode Parent;
        public SortedDictionary<string, TagNode> Children = new(StringComparer.Ordinal);
    }

    private const string OutputPathPattern = "Assets/Scripts/HotUpdate.Core/GameplayTags/{0}Def.gen.cs";

    public static void BuildGameplayTags(GameplayTagDatabase db)
    {
        if (db == null)
            throw new ArgumentNullException(nameof(db));

        string className = ToCSharpIdentifier(db.name, "GameplayTags");
        string buildPath = string.Format(OutputPathPattern, className);

        string directory = Path.GetDirectoryName(buildPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        var tree = BuildTree(db.Tags);
        AssignIds(tree);

        string code = GenerateCode(tree, className);

        File.WriteAllText(buildPath, code, new UTF8Encoding(false));

        AssetDatabase.ImportAsset(buildPath);
        AssetDatabase.Refresh();

        Debug.Log($"GameplayTags generated: {buildPath}");
    }

    private static TagNode BuildTree(IReadOnlyList<string> tags)
    {
        var root = new TagNode
        {
            Name = "Root",
            FullPath = ""
        };

        foreach (string tag in tags)
        {
            if (!GameplayTagDatabase.IsValidTagPath(tag, out var error))
                throw new InvalidOperationException($"非法 GameplayTag: {tag}, reason: {error}");

            var parts = tag.Split('.');
            var current = root;
            string full = "";

            foreach (var part in parts)
            {
                full = string.IsNullOrEmpty(full)
                    ? part
                    : full + "." + part;

                if (!current.Children.TryGetValue(part, out var child))
                {
                    child = new TagNode
                    {
                        Name = part,
                        FullPath = full,
                        Parent = current
                    };

                    current.Children.Add(part, child);
                }

                current = child;
            }
        }

        return root;
    }

    private static void AssignIds(TagNode root)
    {
        AssignRecursive(root);
    }

    private static void AssignRecursive(TagNode node)
    {
        int index = 1;

        foreach (var child in node.Children.Values)
        {
            if (index > 255)
                throw new InvalidOperationException($"同级 GameplayTag 数量超过 255: {node.FullPath}");

            child.Id = index++;
            AssignRecursive(child);
        }
    }

    private static string GenerateCode(TagNode root, string className)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// AUTO GENERATED. DO NOT EDIT.");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        foreach (var child in root.Children.Values)
        {
            GenerateNode(sb, child, 1);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateNode(StringBuilder sb, TagNode node, int indent)
    {
        string ind = new string(' ', indent * 4);

        BuildValueAndMask(node, out uint value, out uint mask);

        string fieldName = node.FullPath.Replace(".", "_");

        sb.AppendLine($"{ind}public static readonly GameplayTag {fieldName} = new GameplayTag(0x{value:X8}u, 0x{mask:X8}u); // @Tag:{node.FullPath}");

        foreach (var child in node.Children.Values)
        {
            GenerateNode(sb, child, indent);
        }
    }

    public static List<string> ParseTagsFromGeneratedCode(string filePath)
    {
        var tags = new List<string>();

        if (!File.Exists(filePath))
            return tags;

        var lines = File.ReadAllLines(filePath);

        foreach (string line in lines)
        {
            int markerIndex = line.IndexOf("// @Tag:", StringComparison.Ordinal);
            if (markerIndex < 0)
                continue;

            string tagPath = line.Substring(markerIndex + "// @Tag:".Length).Trim();
            if (!string.IsNullOrEmpty(tagPath))
                tags.Add(tagPath);
        }

        return tags;
    }

    public static void RestoreTags(GameplayTagDatabase db)
    {
        if (db == null)
            throw new ArgumentNullException(nameof(db));

        string className = ToCSharpIdentifier(db.name, "GameplayTags");
        string filePath = string.Format(OutputPathPattern, className);

        if (!File.Exists(filePath))
        {
            Debug.LogWarning($"找不到生成文件: {filePath}");
            return;
        }

        var tags = ParseTagsFromGeneratedCode(filePath);

        if (tags.Count == 0)
        {
            Debug.LogWarning($"生成文件中未找到任何 Tag 标记: {filePath}");
            return;
        }

        Undo.RecordObject(db, "Restore Gameplay Tags from Code");

        db.ClearTags();

        foreach (string tag in tags)
        {
            db.AddTag(tag);
        }

        EditorUtility.SetDirty(db);
        AssetDatabase.SaveAssetIfDirty(db);

        Debug.Log($"已从生成文件还原 {tags.Count} 个 Tag: {filePath}");
    }

    private static void BuildValueAndMask(TagNode node, out uint value, out uint mask)
    {
        value = 0;
        mask = 0;

        var path = new List<TagNode>(4);

        var cur = node;
        while (cur != null && cur.Parent != null)
        {
            path.Add(cur);
            cur = cur.Parent;
        }

        path.Reverse();

        if (path.Count > 4)
            throw new InvalidOperationException($"GameplayTag 层级超过 4 层: {node.FullPath}");

        int shift = 24;

        foreach (var item in path)
        {
            value |= ((uint)item.Id & 0xFFu) << shift;
            mask |= 0xFFu << shift;
            shift -= 8;
        }
    }

    private static string ToCSharpIdentifier(string raw, string fallback)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return fallback;

        var sb = new StringBuilder(raw.Length + 1);

        char first = raw[0];
        if (!(char.IsLetter(first) || first == '_'))
            sb.Append('_');

        for (int i = 0; i < raw.Length; i++)
        {
            char c = raw[i];
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        string result = sb.ToString();
        return string.IsNullOrEmpty(result) ? fallback : result;
    }
}
#endif